### PR TITLE
Adding TLS support, dependencies updated

### PR DESCRIPTION
**Pull request by namgk**
I'm adding couple of more inputs for configuring TLS certificates and private keys for both server and client.

On a side note, do you need maintainers?

### CODE REVIEW

**Comment by julien-pal** [comment]
Hello, 

Yes it would be nice if you want to be a maintainer !

**Comment by namgk** [comment]
Hi Julien, then could you please give me access to git commit and npm package push?

Thanks

**Comment by julien-pal** [comment]
Hello, 
I gave you the access for the Github repo.
I need your login to add you to the npm project

**Comment by namgk** [comment]
This is my npm profile: nhong. Thanks.

**Pull request merged**
